# Generated by Django 4.0.6 on 2022-09-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_numeroclasse_classe_niveau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeroclasse',
            name='numero_classe',
            field=models.CharField(max_length=100),
        ),
    ]
