# Generated by Django 4.0.6 on 2022-09-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_numeroclasse_numero_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='niveau',
        ),
        migrations.AlterField(
            model_name='classe',
            name='numero_classe',
            field=models.IntegerField(max_length=100),
        ),
        migrations.DeleteModel(
            name='NumeroClasse',
        ),
    ]
