# Generated by Django 4.0.6 on 2022-09-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_classe_niveau_alter_classe_numero_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='numero_classe',
            field=models.IntegerField(),
        ),
    ]
