# Generated by Django 4.0.6 on 2022-09-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_classe_numero_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='numero_classe',
        ),
        migrations.RemoveField(
            model_name='student',
            name='niveau',
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.niveau'),
        ),
    ]
