# Generated by Django 4.0.6 on 2022-09-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_remove_classe_numero_classe_remove_student_niveau_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
    ]
