# Generated by Django 4.0.6 on 2022-09-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_numeroclasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='numero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.numeroclasse'),
        ),
    ]
